#!/usr/bin/env python3
"""
Filter synthetic training utterances (generate_synthetic_utterances.py) for
leakage against Audio2Tool's real test utterances (all 8 tiers).

Why this matters: Audio2Tool's own queries were generated by an LLM from the
same tool function cards this script also prompts from (GPT-5.2/Gemini/Claude
Opus in the paper, Qwen3-32B here) -- so even without either side copying the
other, both draw from the same narrow "natural phrasing for this exact
function" distribution and can coincidentally collide. Training a retriever
on utterances that are near-duplicates of test utterances would silently
inflate its eval numbers.

Two-stage filter per candidate utterance:
  1. Embed candidates + the full test-utterance pool (PromptEOL + last-token
     pooling, embedding_utils.py) and find each candidate's nearest test
     utterance by cosine similarity (one matrix multiply -- cheap even at
     ~3k candidates x ~20k+ test utterances).
  2. Compute word-level normalized edit distance ("WER", edit_distance(words)
     / max(len(ref_words), len(hyp_words))) between the candidate and ONLY
     that nearest neighbor -- not all pairs, which would be O(candidates x
     pool) and much slower for no benefit once the embedding step has already
     found the closest match.
A candidate is dropped if EITHER signal says it's too close: cosine sim
catches semantic paraphrase leakage (different words, same meaning), WER
catches near-verbatim leakage (same words, e.g. minor rewording) that could
score a merely-moderate cosine similarity.

Test pool: `query` field from all 8 tiers' *_data/*.json (confirmed present
on every tier). Tier-7/8's additional per-turn/background query fields
(chat_history, background_query) are NOT included -- a documented
simplification, not a completeness guarantee.

Usage:
    python src/filter_synthetic_utterances.py \\
        --input experiment/synthetic_utterances/raw_Qwen3-32B_k20.json
"""
from __future__ import annotations

import argparse
import glob
import json
from pathlib import Path

import torch
from transformers import AutoModel, AutoTokenizer

from embedding_utils import encode_texts

BASE_DIR = Path(__file__).resolve().parent.parent
TIER_DATA_GLOB = str(BASE_DIR / "data/Audio2Tool_mod/public/*_data/*.json")


def load_test_pool() -> list[str]:
    """Unique `query` strings across all 8 Audio2Tool tiers."""
    seen: set[str] = set()
    for path in sorted(glob.glob(TIER_DATA_GLOB)):
        with open(path) as f:
            rows = json.load(f)
        for row in rows:
            q = row.get("query")
            if q:
                seen.add(q.strip())
    return sorted(seen)


def word_edit_distance(a: list[str], b: list[str]) -> int:
    """Levenshtein distance at word granularity (standard WER numerator)."""
    dp = list(range(len(b) + 1))
    for i, wa in enumerate(a, 1):
        prev, dp[0] = dp[0], i
        for j, wb in enumerate(b, 1):
            cur = dp[j]
            dp[j] = prev if wa == wb else 1 + min(prev, dp[j - 1], dp[j])
            prev = cur
    return dp[-1]


def normalized_word_distance(a: str, b: str) -> float:
    wa, wb = a.lower().split(), b.lower().split()
    if not wa and not wb:
        return 0.0
    return word_edit_distance(wa, wb) / max(len(wa), len(wb), 1)


def main(args: argparse.Namespace) -> None:
    with open(args.input) as f:
        raw = json.load(f)

    candidates: list[tuple[int, int, str]] = []  # (tool_idx, utt_idx, text)
    for ti, tool in enumerate(raw["tools"]):
        for ui, u in enumerate(tool["utterances"]):
            candidates.append((ti, ui, u))
    print(f"Loaded {len(candidates)} candidate utterances across {len(raw['tools'])} tools")

    test_pool = load_test_pool()
    print(f"Loaded {len(test_pool)} unique test utterances (all 8 tiers) as the leakage reference")

    tokenizer = AutoTokenizer.from_pretrained(args.embed_model)
    model = AutoModel.from_pretrained(args.embed_model, torch_dtype=torch.bfloat16).to(args.device)
    model.eval()

    print("Embedding test pool...")
    pool_emb = encode_texts(test_pool, tokenizer, model, args.batch_size, args.max_length)
    print("Embedding candidates...")
    cand_texts = [c[2] for c in candidates]
    cand_emb = encode_texts(cand_texts, tokenizer, model, args.batch_size, args.max_length)

    sims = cand_emb @ pool_emb.T  # [n_candidates, n_pool]
    nearest_sim, nearest_idx = sims.max(dim=-1)

    if args.dry_run:
        import statistics
        cos_vals = nearest_sim.tolist()
        wd_vals = [
            normalized_word_distance(candidates[i][2], test_pool[nearest_idx[i].item()])
            for i in range(len(candidates))
        ]
        for name, vals in [("cosine_sim", cos_vals), ("word_dist", wd_vals)]:
            sv = sorted(vals)
            pct = lambda p: sv[int(len(sv) * p)]  # noqa: E731
            print(
                f"{name}: min={sv[0]:.4f} p10={pct(.1):.4f} p25={pct(.25):.4f} "
                f"median={statistics.median(sv):.4f} p75={pct(.75):.4f} p90={pct(.9):.4f} max={sv[-1]:.4f}"
            )
        return

    kept_per_tool: list[list[str]] = [[] for _ in raw["tools"]]
    dropped = []
    for i, (ti, ui, text) in enumerate(candidates):
        nn_text = test_pool[nearest_idx[i].item()]
        cos = nearest_sim[i].item()
        wdist = normalized_word_distance(text, nn_text)
        too_close = cos > args.cosine_threshold or wdist < args.wer_threshold
        if too_close:
            dropped.append({
                "tool_name": raw["tools"][ti]["tool_name"], "utterance": text,
                "nearest_test_utterance": nn_text, "cosine_sim": round(cos, 4),
                "word_dist": round(wdist, 4),
            })
        else:
            kept_per_tool[ti].append(text)

    print(f"\nDropped {len(dropped)}/{len(candidates)} candidates for test-set leakage "
          f"(cosine>{args.cosine_threshold} or word_dist<{args.wer_threshold})")
    short_tools = [
        (raw["tools"][ti]["tool_name"], len(kept))
        for ti, kept in enumerate(kept_per_tool) if len(kept) < raw["k"]
    ]
    print(f"{len(short_tools)}/{len(raw['tools'])} tool(s) now under the original target k={raw['k']}: "
          f"{short_tools[:10]}")

    out = {
        "source": args.input,
        "embed_model": args.embed_model,
        "cosine_threshold": args.cosine_threshold,
        "wer_threshold": args.wer_threshold,
        "n_candidates": len(candidates),
        "n_dropped": len(dropped),
        "tools": [
            {**{k: v for k, v in tool.items() if k not in ("utterances", "raw_output")},
             "utterances": kept_per_tool[ti]}
            for ti, tool in enumerate(raw["tools"])
        ],
        "dropped_samples": dropped,
    }
    out_path = Path(args.output) if args.output else Path(args.input).with_name(
        Path(args.input).stem + "_filtered.json"
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w") as f:
        json.dump(out, f, indent=2, ensure_ascii=False)
    print(f"Saved -> {out_path}")


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser()
    p.add_argument("--input", required=True, help="Output of generate_synthetic_utterances.py")
    p.add_argument("--embed_model", default="model/Qwen3-0.6B")
    p.add_argument("--device", default="cuda:0")
    p.add_argument("--batch_size", type=int, default=64)
    p.add_argument("--max_length", type=int, default=64)
    p.add_argument("--cosine_threshold", type=float, default=0.999,
                    help="Drop candidate if cosine sim to nearest test utterance exceeds this. "
                         "Deliberately set near a no-op by default: --dry_run on the actual "
                         "3,041-candidate corpus showed PromptEOL cosine sim for these short "
                         "command-style utterances sits in a narrow high band regardless of real "
                         "similarity (p10=0.95, median=0.97, and even clearly-unrelated pairs "
                         "like 'Can we make a detour?' vs 'Can we get a different input on?' "
                         "scored 0.907) -- not discriminative at this text length, so word_dist "
                         "below is the real filter and this is just a near-verbatim-embedding safety net")
    p.add_argument("--wer_threshold", type=float, default=0.30,
                    help="Drop candidate if normalized word-edit-distance to nearest test "
                         "utterance is BELOW this (i.e. too similar). 0.30 was calibrated by "
                         "inspecting the boundary: pairs below it are consistently near-duplicates "
                         "('Find my lost phone' vs 'Find my lost device'), pairs above ~0.33 start "
                         "including clearly-different utterances that just share a sentence template")
    p.add_argument("--output", default=None)
    p.add_argument("--dry_run", action="store_true",
                    help="Print the full nearest-neighbor cosine_sim/word_dist distribution "
                         "(for threshold calibration) instead of filtering")
    return p.parse_args()


if __name__ == "__main__":
    main(parse_args())
